"""
HTTP client for the 1id.com Enrollment API.

Handles all HTTP communication with the 1id.com server, including:
- Enrollment requests (declared and sovereign tiers)
- Identity lookups
- Handle management
- Error response mapping to SDK exceptions

All responses follow the 1id.com API envelope:
  {"ok": true, "data": {...}, "error": null}
  {"ok": false, "data": null, "error": {"code": "...", "message": "..."}}
"""

from __future__ import annotations

import logging
import os
from typing import Any

from . import _http as httpx  # stdlib-backed drop-in (no httpx dependency)

from .credentials import DEFAULT_API_BASE_URL
from .exceptions import (
  EnrollmentError,
  NetworkError,
  raise_from_server_error_response,
)

logger = logging.getLogger("oneid.client")

# -- HTTP client configuration --
# ONEID_HTTP_TIMEOUT_SECONDS lets slow/proxied agent hosts widen the
# window (REAL_USER_ROADBLOCKS R-U 3); default unchanged at 30s.
DEFAULT_HTTP_TIMEOUT_SECONDS = float(
  os.environ.get("ONEID_HTTP_TIMEOUT_SECONDS", "30.0"))
from ._version import USER_AGENT


class OneIDAPIClient:
  """HTTP client for the 1id.com enrollment and identity API.

  Wraps the SDK's stdlib HTTP client (oneid._http) with 1id-specific
  error handling. All methods raise SDK exceptions on failure, never
  raw HTTP errors.

  Args:
      api_base_url: Base URL for the 1id.com API (default: https://1id.com).
      timeout_seconds: HTTP request timeout in seconds.
  """

  def __init__(
    self,
    api_base_url: str = DEFAULT_API_BASE_URL,
    timeout_seconds: float = DEFAULT_HTTP_TIMEOUT_SECONDS,
  ) -> None:
    self.api_base_url = api_base_url.rstrip("/")
    self.timeout_seconds = timeout_seconds

  def _make_request(
    self,
    method: str,
    path: str,
    json_body: dict[str, Any] | None = None,
    headers: dict[str, str] | None = None,
  ) -> dict[str, Any]:
    """Make an HTTP request to the 1id.com API and parse the envelope response.

    Args:
        method: HTTP method ('GET', 'POST', 'DELETE').
        path: API path (e.g., '/api/v1/enroll/declared'). Will be appended to base URL.
        json_body: JSON request body (for POST requests).
        headers: Additional HTTP headers.

    Returns:
        The 'data' field from the successful response envelope.

    Raises:
        NetworkError: If the request fails due to connection issues.
        EnrollmentError (or subclass): If the server returns an error response.
    """
    url = f"{self.api_base_url}{path}"

    request_headers = {
      "User-Agent": USER_AGENT,
      "Accept": "application/json",
    }
    if headers:
      request_headers.update(headers)

    try:
      with httpx.Client(timeout=self.timeout_seconds) as http_client:
        response = http_client.request(
          method=method,
          url=url,
          json=json_body,
          headers=request_headers,
        )
    except httpx.ConnectError as connection_error:
      raise NetworkError(
        f"Could not connect to {self.api_base_url}: {connection_error}"
      ) from connection_error
    except httpx.TimeoutException as timeout_error:
      raise NetworkError(
        f"Request to {url} timed out after {self.timeout_seconds}s: {timeout_error}"
      ) from timeout_error
    except httpx.HTTPError as http_error:
      raise NetworkError(
        f"HTTP error communicating with {url}: {http_error}"
      ) from http_error

    # Parse the response envelope
    try:
      response_body = response.json()
    except Exception as json_parse_error:
      raise NetworkError(
        f"Invalid JSON response from {url} (HTTP {response.status_code}): {json_parse_error}"
      ) from json_parse_error

    # Check for the standard 1id error envelope
    if not response_body.get("ok", False):
      error_info = response_body.get("error", {})
      error_code = error_info.get("code", "UNKNOWN_ERROR")
      error_message = error_info.get("message", f"Server returned HTTP {response.status_code}")
      logger.warning("API error from %s: [%s] %s", url, error_code, error_message)
      raise_from_server_error_response(error_code, error_message)

    return response_body.get("data", {})

  def enroll_declared(
    self,
    software_key_pem: str,
    key_algorithm: str,
    operator_email: str | None = None,
    requested_handle: str | None = None,
    display_name: str | None = None,
    proof_of_possession_signature_b64: str | None = None,
    proof_of_possession_signed_at_unix: int | None = None,
  ) -> dict[str, Any]:
    """Enroll a new identity at the declared trust tier (no HSM required).

    Args:
        software_key_pem: PEM-encoded public key generated by the SDK.
        key_algorithm: Algorithm of the key (e.g., 'ed25519', 'ecdsa-p256').
        operator_email: Optional human operator contact email.
        requested_handle: Optional vanity handle to claim (without '@' prefix).
        display_name: Optional friendly name for the agent.

    Returns:
        Server response data containing identity, credentials, and initial tokens.

    Raises:
        HandleTakenError: If the requested handle is already in use.
        HandleInvalidError: If the requested handle violates naming rules.
        HandleRetiredError: If the requested handle is permanently retired.
        EnrollmentError: If enrollment fails for any other reason.
        NetworkError: If the server cannot be reached.
    """
    request_body: dict[str, Any] = {
      "software_key_pem": software_key_pem,
      "key_algorithm": key_algorithm,
    }
    if operator_email is not None:
      request_body["operator_email"] = operator_email
    if requested_handle is not None:
      request_body["requested_handle"] = requested_handle
    if display_name is not None:
      request_body["display_name"] = display_name
    if proof_of_possession_signature_b64 is not None:
      request_body["proof_of_possession_signature_b64"] = proof_of_possession_signature_b64
      request_body["proof_of_possession_signed_at_unix"] = proof_of_possession_signed_at_unix

    return self._make_request("POST", "/api/v1/enroll/declared", json_body=request_body)

  def enroll_begin(
    self,
    ek_certificate_pem: str,
    ak_public_key_pem: str,
    ak_tpmt_public_b64: str = "",
    ek_public_key_pem: str = "",
    ek_certificate_chain_pem: list[str] | None = None,
    hsm_type: str = "tpm",
    operator_email: str | None = None,
    requested_handle: str | None = None,
    display_name: str | None = None,
  ) -> dict[str, Any]:
    """Begin TPM/HSM-based enrollment (sovereign/virtual tiers).

    This is the first step of the two-phase enrollment flow. The server
    validates the attestation chain and returns a credential activation
    challenge (credential_blob + encrypted_secret) that the TPM must
    decrypt via ActivateCredential to prove possession.

    Args:
        ek_certificate_pem: PEM-encoded EK certificate (TPM) or attestation cert (YubiKey).
        ak_public_key_pem: PEM-encoded public key of the Attestation Identity Key.
        ak_tpmt_public_b64: Base64-encoded marshaled TPMT_PUBLIC of the AK.
            Required for TPM enrollment (server uses it to compute AK Name for MakeCredential).
        ek_certificate_chain_pem: Optional intermediate CA certs found on the client (best-effort).
        hsm_type: Type of HSM ('tpm', 'yubikey', 'nitrokey', etc.).
        operator_email: Optional human operator contact email.
        requested_handle: Optional vanity handle to claim.
        display_name: Optional friendly name for the agent.

    Returns:
        Server response containing enrollment_session_id, credential_blob,
        encrypted_secret, trust_tier classification, and session expiry.

    Raises:
        AlreadyEnrolledError: If this HSM is already enrolled.
        HandleTakenError: If the requested handle is taken.
        EnrollmentError: If the EK cert is invalid or chain is untrusted.
        NetworkError: If the server cannot be reached.
    """
    request_body: dict[str, Any] = {
      "ek_certificate_pem": ek_certificate_pem,
      "ek_public_key_pem": ek_public_key_pem,
      "ak_public_key_pem": ak_public_key_pem,
      "ak_tpmt_public_b64": ak_tpmt_public_b64,
      "hsm_type": hsm_type,
    }
    if ek_certificate_chain_pem:
      request_body["ek_certificate_chain_pem"] = ek_certificate_chain_pem
    if operator_email is not None:
      request_body["operator_email"] = operator_email
    if requested_handle is not None:
      request_body["requested_handle"] = requested_handle
    if display_name is not None:
      request_body["display_name"] = display_name

    return self._make_request("POST", "/api/v1/enroll/begin", json_body=request_body)

  def enroll_begin_piv(
    self,
    attestation_cert_pem: str,
    attestation_chain_pem: list[str],
    signing_key_public_pem: str,
    hsm_type: str = "yubikey",
    operator_email: str | None = None,
    requested_handle: str | None = None,
    display_name: str | None = None,
  ) -> dict[str, Any]:
    """Begin PIV-based enrollment (portable tier).

    This is the first step of the two-phase PIV enrollment flow. The server
    validates the attestation certificate chain against the Yubico Root CA,
    checks the anti-Sybil registry by device serial number, and returns a
    nonce challenge that the PIV key must sign to prove possession.

    Args:
        attestation_cert_pem: PEM-encoded slot attestation certificate from the PIV device.
        attestation_chain_pem: List of PEM-encoded intermediate CA certs (typically the F9 cert).
        signing_key_public_pem: PEM-encoded ECDSA public key of the PIV signing key (slot 9a).
        hsm_type: Type of PIV device ('yubikey').
        operator_email: Optional human operator contact email.
        requested_handle: Optional vanity handle to claim.
        display_name: Optional friendly name for the agent.

    Returns:
        Server response containing enrollment_session_id, nonce_challenge,
        trust_tier classification, device_serial, and session expiry.

    Raises:
        AlreadyEnrolledError: If this PIV device serial is already enrolled.
        HandleTakenError: If the requested handle is taken.
        EnrollmentError: If the attestation cert is invalid or chain is untrusted.
        NetworkError: If the server cannot be reached.
    """
    request_body: dict[str, Any] = {
      "attestation_cert_pem": attestation_cert_pem,
      "attestation_chain_pem": attestation_chain_pem,
      "signing_key_public_pem": signing_key_public_pem,
      "hsm_type": hsm_type,
    }
    if operator_email is not None:
      request_body["operator_email"] = operator_email
    if requested_handle is not None:
      request_body["requested_handle"] = requested_handle
    if display_name is not None:
      request_body["display_name"] = display_name

    return self._make_request("POST", "/api/v1/enroll/begin/piv", json_body=request_body)

  def enroll_begin_enclave(
    self,
    enclave_public_key_pem: str,
    operator_email: str | None = None,
    requested_handle: str | None = None,
    display_name: str | None = None,
  ) -> dict[str, Any]:
    """Begin enclave enrollment by submitting the Secure Enclave public key.

    Server validates the key format, generates a nonce challenge, and returns
    a session ID. The client must sign the nonce with the Enclave key and
    submit it to enroll_activate().

    Args:
        enclave_public_key_pem: PEM-encoded ECDSA P-256 public key from the Secure Enclave.
        operator_email: Optional operator contact email.
        requested_handle: Optional vanity handle.
        display_name: Optional friendly agent name.

    Returns:
        Server response with enrollment_session_id, nonce_challenge, trust_tier.
    """
    request_body: dict[str, Any] = {
      "enclave_public_key_pem": enclave_public_key_pem,
    }
    if operator_email:
      request_body["operator_email"] = operator_email
    if requested_handle:
      request_body["requested_handle"] = requested_handle
    if display_name:
      request_body["display_name"] = display_name

    return self._make_request("POST", "/api/v1/enroll/enclave/begin", json_body=request_body)

  def enroll_activate(
    self,
    enrollment_session_id: str,
    decrypted_credential: str | None = None,
    certify_info_b64: str | None = None,
    certify_signature_b64: str | None = None,
  ) -> dict[str, Any]:
    """Complete HSM-based enrollment by proving HSM possession.

    TPM: send certify_info_b64 + certify_signature_b64 from the
    import-and-certify proof (no elevation). PIV/enclave: send the nonce
    signature as decrypted_credential.

    Returns:
        Server response containing identity, credentials, initial tokens,
        message_for_agent and handle_summary.
    """
    body: dict[str, Any] = {"enrollment_session_id": enrollment_session_id}
    if decrypted_credential is not None:
      body["decrypted_credential"] = decrypted_credential
    if certify_info_b64 is not None:
      body["certify_info"] = certify_info_b64
      body["certify_signature"] = certify_signature_b64
    return self._make_request("POST", "/api/v1/enroll/activate", json_body=body)

  def recover_begin(
    self,
    ek_certificate_pem: str,
    ak_public_key_pem: str,
    ak_tpmt_public_b64: str,
    ek_public_key_pem: str = "",
    ek_certificate_chain_pem: list[str] | None = None,
  ) -> dict[str, Any]:
    """Begin TPM-based identity recovery.

    When a machine has lost credentials.json but still has its TPM, this
    endpoint creates a MakeCredential challenge to prove hardware possession
    and recover the existing identity's credentials.
    """
    request_body: dict[str, Any] = {
      "ek_certificate_pem": ek_certificate_pem,
      "ak_public_key_pem": ak_public_key_pem,
      "ak_tpmt_public_b64": ak_tpmt_public_b64,
    }
    if ek_public_key_pem:
      request_body["ek_public_key_pem"] = ek_public_key_pem
    if ek_certificate_chain_pem:
      request_body["ek_certificate_chain_pem"] = ek_certificate_chain_pem

    return self._make_request("POST", "/api/v1/enroll/recover", json_body=request_body)

  def recover_begin_sign_based(
    self,
    ek_certificate_pem: str,
    ak_public_key_pem: str,
    ak_tpmt_public_b64: str,
    ek_public_key_pem: str = "",
    ek_certificate_chain_pem: list[str] | None = None,
  ) -> dict[str, Any]:
    """Begin sign-based TPM identity recovery (NO elevation needed).

    Instead of MakeCredential (which requires ActivateCredential and therefore
    elevation on Windows), the server issues a random nonce. The client signs
    it with the TPM AK (userspace operation after one-time setup-tbs) and sends
    the signature back via recover_activate_sign_based().
    """
    request_body: dict[str, Any] = {
      "ek_certificate_pem": ek_certificate_pem,
      "ak_public_key_pem": ak_public_key_pem,
      "ak_tpmt_public_b64": ak_tpmt_public_b64,
    }
    if ek_public_key_pem:
      request_body["ek_public_key_pem"] = ek_public_key_pem
    if ek_certificate_chain_pem:
      request_body["ek_certificate_chain_pem"] = ek_certificate_chain_pem

    return self._make_request("POST", "/api/v1/enroll/recover/sign-based", json_body=request_body)

  def recover_activate_sign_based(
    self,
    recovery_session_id: str,
    signed_nonce_b64: str,
  ) -> dict[str, Any]:
    """Complete sign-based identity recovery by submitting the AK signature over the nonce.

    The server verifies the signature against the stored AK public key.
    Returns fresh credentials (rotated client_secret) for the recovered identity.
    """
    return self._make_request("POST", "/api/v1/enroll/recover/sign-based/activate", json_body={
      "enrollment_session_id": recovery_session_id,
      "decrypted_credential": signed_nonce_b64,
    })

  def recover_begin_piv(
    self,
    attestation_cert_pem: str,
    attestation_chain_pem: list[str],
    signing_key_public_pem: str,
    hsm_type: str = "yubikey",
  ) -> dict[str, Any]:
    """Begin PIV-based identity recovery."""
    return self._make_request("POST", "/api/v1/enroll/recover/piv", json_body={
      "hsm_type": hsm_type,
      "attestation_cert_pem": attestation_cert_pem,
      "attestation_chain_pem": attestation_chain_pem,
      "signing_key_public_pem": signing_key_public_pem,
    })

  def recover_activate(
    self,
    recovery_session_id: str,
    decrypted_credential: str,
  ) -> dict[str, Any]:
    """Complete identity recovery by proving hardware possession.

    Returns fresh credentials (rotated client_secret) for the recovered identity.
    """
    return self._make_request("POST", "/api/v1/enroll/recover/activate", json_body={
      "enrollment_session_id": recovery_session_id,
      "decrypted_credential": decrypted_credential,
    })

  def get_identity(self, agent_id: str) -> dict[str, Any]:
    """Look up public identity information for an agent.

    Args:
        agent_id: The agent's canonical ID (e.g., 'id-xpwsb-rqgdz-vctkm-nfjhx').

    Returns:
        Public identity data (canonical_id, handle, trust_tier, etc.).
    """
    return self._make_request("GET", f"/api/v1/identity/{agent_id}")

  def get_device_certificate_chain(
    self,
    device_fingerprint: str,
    access_token: str,
  ) -> dict[str, Any]:
    """Fetch the per-device certificate chain for a specific device.

    Phase 2: Each device bound to an identity has its own certificate chain
    where the leaf cert's public key matches that device's signing key.
    """
    return self._make_request(
      "GET",
      f"/api/v1/identity/devices/{device_fingerprint}/certificate",
      headers={"Authorization": access_token},  # a Token: signed by _http (a str would be refused)
    )

  def get_all_device_certificate_chains(
    self,
    access_token: str,
  ) -> dict[str, Any]:
    """Fetch all per-device certificate chains for this identity.

    Returns a dict with device_certificate_chains keyed by device fingerprint.
    """
    return self._make_request(
      "GET",
      "/api/v1/identity/devices/certificates",
      headers={"Authorization": access_token},  # a Token: signed by _http (a str would be refused)
    )

  def check_handle_availability(self, handle_name: str) -> dict[str, Any]:
    """Check whether a vanity handle is available.

    Args:
        handle_name: The handle to check (without '@' prefix).

    Returns:
        Dict with 'status' field: 'available', 'taken', or 'retired'.
    """
    return self._make_request("GET", f"/api/v1/handle/{handle_name}")
